import { SxProps } from '@mui/system';

export const UserMealPlanStyles: { [key: string]: SxProps } = {
  userMealPlanContainer: {
    color: 'common.white',
    background: 'background.paper',
    bottom: 0,
    top: '124px',
    display: 'flex',
    width: '100%',
    height: 'fit-content',
    mb: '84px',
  },

  switchButtonContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: { md: 'fit-content', xl: '500px' },
    mt: '34px',
    m: '16px auto 0 auto',
  },
  todayDietAndCalenderContainer: {
    width: { xl: '500px', lg: '50%' },
    minWidth: '390px',
    pt: '16px',
    position: 'relative',
    mr: '16px',
    display: 'flex',
    flexDirection: { lg: 'column', md: 'row' },
    gap: '10px',
  },
  todayDietHeader: {
    background: '#131336',
    p: '25px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: '8px 8px 0 0 ',
  },
  todayDietTitle: { color: 'common.white' },
  todayDietDate: { color: 'common.dark', display: 'flex' },
  todayBreakFastLunch: { backgroundColor: 'background.light', p: '20px 32px', borderRadius: '0 0 8px 8px' },
  todayBreakfastContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  todayBreakfastTitle: { alignSelf: 'flex-start' },
  todayBreakfastItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    mb: '12px',
    mt: '24px',
    justifyContent: 'space-between',
    cursor: 'pointer',
  },
  todayBreakfastImageTitle: { display: 'flex', alignItems: 'center' },
  todayBreakfastItemTitle: { ml: '24px', width: '224px' },
  addMoreItemsButton: {
    borderRadius: '32px',
    background: 'white',
    border: '1px solid #D0D0D7',
    color: 'primary.dark',

    p: '10px 24px',
    '&:hover': {
      backgroundColor: 'background.paper',
      boxShadow: 'none',
    },
  },
  calendarContainer: {
    border: '2px solid #B8B8C3',
    ml: { md: '10px' },
    mt: { xl: '24px', md: '0px' },
    borderRadius: '4px',
    maxHeight: '350px',
  },
  accordionContainer: {
    width: { md: '100%', xl: '70%' },
    mr: 0,
    height: `calc(100vh - 130px)`,
    pt: '16px',
    overflow: 'scroll',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    mt: { xl: '0px', md: '32px', sm: '32px', lg: '0px' },
  },
  accordion: {
    borderRadius: '12px',
    mb: 1,

    '& .MuiBox-root': { border: 'none' },
    '& .Mui-expanded': { borderRadius: '12px 12px 0 0' },
    '&::before': { display: 'none' },
  },
  accordionSummary: {
    borderRadius: '12px ',
    mb: '0',
    backgroundColor: ' #F4F5FC',
  },
  accordionSummaryItem: { display: 'flex' },
  accordionSummaryTitle: { flexShrink: 0, textTransform: 'capitalize' },
  accordionSummaryTitleDate: { ml: '6px' },
  accordionDetailsContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  accordionDetailsHeader: { width: '100%', display: 'flex', justifyContent: 'space-between' },
  accordionDetailsTitle: { mb: '12px' },
  accordionDietItems: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    borderBottom: '1px solid #EFEFEF',
    mb: '12px',
    cursor: 'pointer',
  },
  accordionDietItemTitle: { ml: '24px' },
  addMoreButtonContainer: { display: 'flex', justifyContent: 'center' },
};
