export const ROUTE = {
  DASHBOARD: '/dashboard',
  SIGN_IN: '/user/signin',
  SIGN_UP: '/user/signup/',
  LOGIN: '/user/login',
  HOME: '/',
  RESOURCE_DETAILS: '/user/learn/resources/detail/',
  RECIPE_DETAILS: '/user/learn/recipe/',
  RECORD: '/user/record/new-data/',
  COMMUNITY: '/user/community/feeds/',
  CHAT: '/user/community/chat',
  FRIEND: '/user/community/friends/requests',
  ME: '/user/me/mePage/',
  PROFILE: '/profile/',
  CALLBACK: '/callback',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  PRIVACY_POLICY: '/privacy-policy',
};
