import { SxProps } from '@mui/system';

export const GenericShareModaStyles: { [key: string]: SxProps } = {
  modalBackdrop: { postion: 'fixed', left: 0, top: '0px', width: '100%', height: '100%', zIndex: 9999 },
  modalContainerOutermost: { position: 'absolute', width: '100%', height: '100%', top: 0, left: 0 },
  modalContainer: { p: '24px 32px', borderRadius: '12px', backgroundColor: '#FFFF' },
  modalTitle: { display: 'flex', justifyContent: 'space-between' },
  profileInfo: { display: 'flex', alignItems: 'center', mt: '16px' },
  profileName: { ml: '12px', textTransform: 'capitalize' },
  shareDesc: {
    mt: '12px',
    borderRadius: '16px',
    width: '100%',
    textIndent: '12px',
    marginBottom: '24px',
    outline: 'none',
    backgroundColor: '#F4F5FC',
    '& .MuiInputBase-input.Mui-disabled': {
      WebkitTextFillColor: '#000000',
    },
    '& fieldset': { border: 'none' },
  },
  descriptionText: { textAlign: 'left', mb: '16px' },
  sharedImage: {
    position: 'relative',
    width: '100%',
    height: '300px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  sharedBadgeBG: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '4px',
    background: 'radial-gradient(60.1% 66.93% at 86.5% 66.67%, #FDE078 0%, #FDB839 100%) ',
  },
  badgeTitle: { mt: '12px', mb: '8px' },
  playIconContainer: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%,-50%)',
    width: 'fit-content',
    zIndex: 2,
    cursor: 'pointer',
  },
  postFeedContainer: { display: 'flex', alignItems: 'center', mt: '16px' },
  feedProfileImage: { position: 'relative', width: '48px', height: '48px', borderRadius: '50%' },
  defaultImageStyle: { width: '42px', height: '42px' },
  marginLeft12: { ml: '12px' },
  authorNameShareModal: { textTransform: 'capitalize', ml: '12px' },
  buttonContainer: { display: 'flex', justifyContent: 'center', mt: '24px' },
  loadingButtonStyle: {
    paddingY: 2,
    paddingX: 3.5,
    textTransform: 'capitalize',
    fontSize: '16px',
    background: '#0C72E0',
    width: 'fit-content',
    borderRadius: '40px',
  },
};
